#!/usr/bin/python
#-*- coding: utf-8 -*-


# this dictionary contains hero name extracted from items image paths
# and their corresponding name in the hero api endpoint
# item['image_inventory'] extracted hero name -> hero['name']

HERO_DICT = {
     u'alchemist': 'npc_dota_hero_alchemist',
     u'antimage': 'npc_dota_hero_antimage',
     u'axe': 'npc_dota_hero_axe',
     #u'bane': 'npc_dota_hero_bane', # no items yet
     u'batrider': 'npc_dota_hero_batrider',
     u'beastmaster': 'npc_dota_hero_beastmaster',
     u'blood_seeker': 'npc_dota_hero_bloodseeker',
     u'bounty_hunter': 'npc_dota_hero_bounty_hunter',
     u'brewmaster': 'npc_dota_hero_brewmaster',
     u'broodmother': 'npc_dota_hero_broodmother',
     u'centaur': 'npc_dota_hero_centaur',
     u'chen': 'npc_dota_hero_chen',
     u'clinkz': 'npc_dota_hero_clinkz',
     u'crystal_maiden': 'npc_dota_hero_crystal_maiden',
     u'dazzle': 'npc_dota_hero_dazzle',
     u'death_prophet': 'npc_dota_hero_death_prophet',
     u'disruptor': 'npc_dota_hero_disruptor',
     u'doom': 'npc_dota_hero_doom_bringer',
     u'dragon_knight': 'npc_dota_hero_dragon_knight',
     u'drow': 'npc_dota_hero_drow_ranger' ,
     u'enchantress': 'npc_dota_hero_enchantress',
     u'faceless_void': 'npc_dota_hero_faceless_void',
     u'furion': 'npc_dota_hero_furion',
     u'huskar': 'npc_dota_hero_huskar',
     u'invoker': 'npc_dota_hero_invoker',
     u'juggernaut': 'npc_dota_hero_juggernaut',
     u'keeper_of_the_light': 'npc_dota_hero_keeper_of_the_light',
     u'kunkka': 'npc_dota_hero_kunkka',
     u'lanaya': 'npc_dota_hero_templar_assassin',
     u'leshrac': 'npc_dota_hero_leshrac',
     u'lich': 'npc_dota_hero_lich',
     u'lina': 'npc_dota_hero_lina',
     u'lion': 'npc_dota_hero_lion',
     u'lone_druid': 'npc_dota_hero_lone_druid',
     u'lycan': 'npc_dota_hero_lycan',
     u'meepo': 'npc_dota_hero_meepo',
     u'mirana': 'npc_dota_hero_mirana',
     u'morphling': 'npc_dota_hero_morphling',
     u'necrolyte': 'npc_dota_hero_necrolyte',
     u'nerubian_assassin': 'npc_dota_hero_nyx_assassin',
     u'obsidian_destroyer': 'npc_dota_hero_obsidian_destroyer',
     u'ogre_magi': 'npc_dota_hero_ogre_magi',
     u'omniknight': 'npc_dota_hero_omniknight',
     u'phantom_assassin': 'npc_dota_hero_phantom_assassin',
     u'phantom_lancer': 'npc_dota_hero_phantom_lancer',
     u'pudge': 'npc_dota_hero_pudge',
     u'queenofpain': 'npc_dota_hero_queenofpain',
     u'rikimaru': 'npc_dota_hero_riki',
     u'rubick': 'npc_dota_hero_rubick',
     u'sand_king': 'npc_dota_hero_sand_king',
     u'shadow_demon': 'npc_dota_hero_shadow_demon',
     u'shadowshaman': 'npc_dota_hero_shadow_shaman',
     u'silencer': 'npc_dota_hero_silencer',
     u'siren': 'npc_dota_hero_naga_siren',
     u'skeleton_king': 'npc_dota_hero_skeleton_king',
     u'slardar': 'npc_dota_hero_slardar',
     u'slark': 'npc_dota_hero_slark',
     u'sniper': 'npc_dota_hero_sniper',
     u'spectre': 'npc_dota_hero_spectre',
     u'spirit_breaker': 'npc_dota_hero_spirit_breaker',
     u'storm_spirit': 'npc_dota_hero_storm_spirit',
     u'sven': 'npc_dota_hero_sven',
     u'tidehunter': 'npc_dota_hero_tidehunter',
     u'tiny': 'npc_dota_hero_tiny',
     u'twin_headed_dragon': 'npc_dota_hero_jakiro',
     u'ursa': 'npc_dota_hero_ursa',
     u'warlock': 'npc_dota_hero_warlock',
     u'weaver': 'npc_dota_hero_weaver',
     u'windrunner': 'npc_dota_hero_windrunner',
     u'witchdoctor': 'npc_dota_hero_witch_doctor'}
